import type { Metadata } from 'next';
import { Header } from '@/components/shared/header';
import Styles from '../../../page.module.scss';
import { Container } from '@/components/shared';
import { TopBarPage } from '@/components/ui/topBar';

export const metadata: Metadata = {
  title: 'Voltex | Product',
  description: 'Generated by create next app',
};

export default function RootLayoutCart({
  children,
  params: { id },
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  return (
    <main className={Styles.product}>
      <Container>
        <Header hasSearch={false} hasCart={false} hasImage={false} />
        <TopBarPage productId={Number(id)} />
        {children}
      </Container>
    </main>
  );
}
