import type { Metadata } from "next";
import { Header } from "@/components/header";
import Styles from "../../../page.module.scss";
import { Container } from "@/components";
import { TopBarPage } from "@/components/topBar";
import { LayoutProps } from "../../../../../.next/types/app/(product)/Product/[id]/Characteristics/page";

export const metadata: Metadata = {
  title: "Voltex | Product",
  description: "Generated by create next app",
};

export default async function RootLayoutCart({
  children,
  params,
}: LayoutProps) {
  const { id } = await params;
  return (
    <main className={Styles.product}>
      <Container>
        <Header hasSearch={false} hasCart={false} hasImage={false} />
        <TopBarPage productId={Number(id)} />
        {children}
      </Container>
    </main>
  );
}
