import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import Providers from "../../providers/provider";
import { Provider } from "@/components/providers";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Voltex | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Provider>
          <Providers>
            {" "}
            <main>
              {children}
              <Toaster />
            </main>
          </Providers>
        </Provider>
      </body>
    </html>
  );
}
